const PDFDocument = require('pdfkit');

const generateReportPDF = (report, stream) => {
  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(stream);

  // Title
  doc.fontSize(22).font('Helvetica-Bold').text('OutpostClaude Sales Report', { align: 'center' });
  doc.moveDown(0.5);

  const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'];
  const title = report.title || `${monthNames[report.month - 1]} ${report.year}`;
  doc.fontSize(14).font('Helvetica').text(title, { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor('#666').text(`Generated: ${new Date(report.created_at).toLocaleDateString()}`, { align: 'center' });
  doc.moveDown(1);

  const data = report.data || {};

  // Summary box
  doc.fillColor('#000').fontSize(14).font('Helvetica-Bold').text('Summary');
  doc.moveDown(0.3);
  doc.fontSize(11).font('Helvetica');
  doc.text(`Total Orders: ${data.total_orders || 0}`);
  doc.text(`Total Revenue: $${(data.total_revenue || 0).toFixed(2)}`);
  doc.text(`Card Payments: ${data.card_payments || 0}`);
  doc.text(`Online Banking Payments: ${data.banking_payments || 0}`);
  doc.moveDown(1);

  // Order details table
  if (data.orders && data.orders.length > 0) {
    doc.fontSize(14).font('Helvetica-Bold').text('Order Details');
    doc.moveDown(0.5);

    // Table header
    const tableTop = doc.y;
    const colWidths = [120, 100, 100, 90, 90];
    const headers = ['Customer', 'Date', 'Total', 'Payment', 'Status'];

    doc.fontSize(9).font('Helvetica-Bold');
    let xPos = 50;
    headers.forEach((header, i) => {
      doc.text(header, xPos, tableTop, { width: colWidths[i] });
      xPos += colWidths[i];
    });

    doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke('#ccc');

    // Table rows
    doc.font('Helvetica').fontSize(9);
    let yPos = tableTop + 22;

    data.orders.forEach((order) => {
      if (yPos > 700) {
        doc.addPage();
        yPos = 50;
      }

      xPos = 50;
      const row = [
        order.customer_name || 'N/A',
        order.date ? new Date(order.date).toLocaleDateString() : 'N/A',
        `$${(order.total || 0).toFixed(2)}`,
        order.payment_method || 'N/A',
        order.status || 'N/A',
      ];

      row.forEach((cell, i) => {
        doc.text(cell, xPos, yPos, { width: colWidths[i] });
        xPos += colWidths[i];
      });

      yPos += 18;
    });
  }

  // Footer
  doc.moveDown(2);
  doc.fontSize(8).fillColor('#999').text('This report was generated by OutpostClaude E-Commerce System', { align: 'center' });

  doc.end();
  return doc;
};

module.exports = { generateReportPDF };
